export const LOADSCREEN_TYPES = {
  LOADSCREEN_ON: '[REDUX][LOADSCREEN_ON]',
  LOADSCREEN_OFF: '[REDUX][LOADSCREEN_OFF]',
}
export const SELECTED_COUNTRY_TYPES = {
  SET_SELECTED_VAULUE: '[REDUX][SET_SELECTED_VAULUE]',
  CLEAR_SELECTED_VALUE: '[REDUX][CLEAR_SELECTED_VALUE]',
}

export const VITYA_DISLIKE_TYPES = {
  DISLIKE_ON: '[REDUX][DISLIKE_ON]',
  DISLIKE_OFF: '[REDUX][DISLIKE_OFF]',
}

export const SETMENU_SWITCH_TYPES = {
  SETMENU_SWITCH: '[REDUX][SETMENU_SWITCH]',
}
export const SETMOBILE_SWITCH_TYPES = {
  SETMOBILE_SWITCH: '[REDUX][SETMOBILE_SWITCH]',
}
export const CLEARFULLDRUG_TYPE = {
  CLEAR: '[REDUX][CLEAR]',
}
export const SET_DRUGS_TYPES = {
  SET_DRUGS: '[SAGA][SET_DRUGS]',
  USER_FETCH_SUCCEEDED: '[SAGA][USER_FETCH_SUCCEEDED]',
  USER_FETCH_FAILED: '[SAGA][USER_FETCH_FAILED]',
  USER_FETCH_REQUESTED: '[SAGA][USER_FETCH_REQUESTED]',
  SEARCH_DRUGS_SUCCEEDED: '[SAGA][SEARCH_DRUGS_SUCCEDED]',
  SEARCH_DRUGS_REQUESTED: '[SAGA][SEARCH_DRUGS_REQUESTED]',
  SET_SEARCH_LIST: '[SAGA][SET_SEARCH_LIST]',
  GET_ALL_COUNTRIES_REQUESTED: '[SAGA][GET_ALL_COUNTRIES_REQUESTED]',
  GET_ALL_COUNTRIES_SUCCEEDED: '[SAGA][GET_ALL_COUNTRIES_SUCCEEDED]',
  GET_ALL_COUNTRIES_FAILED: '[SAGA][GET_ALL_COUNTRIES_FAILED]',
  SET_ALL_COUNTRIES_LIST: '[SAGA][SET_ALL_COUNTRIES_LIST]',
  SET_SEARCH_FULL_DRUG: '[SAGA][SET_SEARCH_FULL_DRUG]',
  SEARCH_DRUGS_FULL_REQUESTED: '[SAGA][SEARCH_DRUGS_FULL_REQUESTED]',
  SEARCH_DRUGS_FULL_SUCCEEDED: '[SAGA][SEARCH_DRUGS_FULL_SUCCEEDED]',
  SEARCH_DRUGS_FULL_FAILED: '[SAGA][SEARCH_DRUGS_FULL_FAILED]',
  SEARCH_DRUGS_CLEAR: '[SAGA][SEARCH_DRUGS_CLEAR]',
  SET_ANALOGS: '[SAGA][SET_ANALOGS]',
  GET_ANALOGS_REQUESTED: '[SAGA][GET_ANALOGS_REQUESTED]',
  GET_ANALOGS_SUCCEEDED: '[SAGA][GET_ANALOGS_SUCCEEDED]',
  GET_ANALOGS_FAILED: '[SAGA][GET_ANALOGS_FAILED]',
  SET_PICTURES: '[SAGA][SET_PICTURES]',
  PUT_PICTURES_REQUESTED: '[SAGA][PUT_PICTURES_REQUESTED]',
  PUT_PICTURES_SUCCEEDED: '[SAGA][PUT_PICTURES_SUCCEEDED]',
  PUT_PICTURES_FAILED: '[SAGA][PUT_PICTURES_FAILED]',
}

export const SEARCH_PARAMS_TYPES = {
  SET_SEARCH_PARAMS: '[REDUX][SET_SEARCH_PARAMS]',
  SET_PAGE_NUMBER: '[REDUX][SET_PAGE_NUMBER]',
  CLEAR_PAGE_NUMBER: '[REDUX][CLEAR_OAGE_NUMBER]',
}

export const SET_POPULARCHECK_TYPES = {
  SET_POPULARCHECK: '[REDUX][SET_POPULARCHECK]',
  CLEAR: '[REDUX][CLEAR]',
}
